import type { LocationPin, LocationFull, User } from './types';
import { LocationCategory } from './types';

export const MOCK_USER: User = {
  id: 'user-123',
  username: 'GhostHunterX',
  avatarUrl: 'https://picsum.photos/seed/user/100/100',
  investigationScore: 1337,
  badges: ['EVP Specialist', 'History Buff'],
};

export const MOCK_LOCATION_PINS: LocationPin[] = [
  { id: 1, name: 'The Winchester Mystery House', coordinates: [37.3184, -121.9513], category: LocationCategory.HAUNTED },
  { id: 2, name: 'Alcatraz Island', coordinates: [37.8270, -122.4230], category: LocationCategory.CRIME },
  { id: 3, name: 'The Villisca Axe Murder House', coordinates: [40.9329, -94.9750], category: LocationCategory.MYSTERY },
  { id: 4, name: 'Eastern State Penitentiary', coordinates: [39.9683, -75.1725], category: LocationCategory.HAUNTED },
  { id: 5, name: 'Lizzie Borden House', coordinates: [41.7006, -71.1565], category: LocationCategory.CRIME },
  { id: 6, name: "Jack the Ripper's London", coordinates: [51.5186, -0.0740], category: LocationCategory.MYSTERY },
  { id: 7, name: 'Old Town Saloon (User Submitted)', coordinates: [34.0522, -118.2437], category: LocationCategory.USER },
  { id: 8, name: 'Lord Baltimore Hotel', coordinates: [39.2885, -76.6180], category: LocationCategory.HAUNTED },
  { id: 9, name: 'Castillo de San Marcos', coordinates: [29.8976, -81.3113], category: LocationCategory.HAUNTED },
  { id: 10, name: 'St. Augustine Lighthouse', coordinates: [29.8851, -81.2882], category: LocationCategory.HAUNTED },
  { id: 11, name: 'Old Jail, St. Augustine', coordinates: [29.9079, -81.3149], category: LocationCategory.HAUNTED },
  { id: 12, name: 'Gettysburg Battlefield', coordinates: [39.8055, -77.2498], category: LocationCategory.HAUNTED },
  { id: 13, name: 'Salem Witch Trials Memorial', coordinates: [42.5201, -70.8950], category: LocationCategory.HAUNTED },
  { id: 14, name: 'The Conjuring House', coordinates: [41.9778, -71.6826], category: LocationCategory.HAUNTED },
  { id: 15, name: 'Old New-Gate Prison', coordinates: [41.9213, -72.7483], category: LocationCategory.HAUNTED },
  { id: 16, name: 'Dock Street Theatre', coordinates: [32.7770, -79.9298], category: LocationCategory.HAUNTED },
  { id: 17, name: 'The Marshall House', coordinates: [32.0784, -81.0908], category: LocationCategory.HAUNTED },
  { id: 18, name: 'Trans-Allegheny Lunatic Asylum', coordinates: [39.0435, -80.4728], category: LocationCategory.HAUNTED },
  { id: 19, name: 'Sleepy Hollow Cemetery', coordinates: [41.0950, -73.8631], category: LocationCategory.HAUNTED },
  { id: 20, name: 'The Black Dahlia Murder', coordinates: [34.0637, -118.3288], category: LocationCategory.MYSTERY },
  { id: 21, name: 'Zodiac Killer Territory', coordinates: [38.1041, -122.2566], category: LocationCategory.MYSTERY },
  { id: 22, name: 'JonBenét Ramsey House', coordinates: [40.0084, -105.2760], category: LocationCategory.MYSTERY },
  { id: 23, name: 'Isabella Stewart Gardner Museum', coordinates: [42.3380, -71.0991], category: LocationCategory.CRIME },
  { id: 24, name: 'D.B. Cooper Skyjacking', coordinates: [45.9929, -122.7012], category: LocationCategory.MYSTERY },
  { id: 25, name: 'Disappearance of Jimmy Hoffa', coordinates: [42.5484, -83.2880], category: LocationCategory.MYSTERY },
  { id: 26, name: 'Chicago Tylenol Murders', coordinates: [42.0334, -87.9167], category: LocationCategory.CRIME },
  { id: 27, name: 'Long Island Serial Killer', coordinates: [40.6490, -73.3440], category: LocationCategory.MYSTERY },
  { id: 28, name: 'Keddie Cabin Murders', coordinates: [39.9918, -120.9599], category: LocationCategory.MYSTERY },
  { id: 29, name: 'The Boy in the Box', coordinates: [39.9955, -75.1182], category: LocationCategory.MYSTERY },
  { id: 30, name: 'Texarkana Moonlight Murders', coordinates: [33.4418, -94.0660], category: LocationCategory.MYSTERY },
  { id: 31, name: 'Bonny Lee Bakley Murder', coordinates: [34.1444, -118.3842], category: LocationCategory.MYSTERY },
  { id: 32, name: 'Chandra Levy Disappearance', coordinates: [38.9221, -77.0469], category: LocationCategory.MYSTERY },
  { id: 33, name: 'Marsha Brantley Disappearance', coordinates: [35.1584, -84.8519], category: LocationCategory.MYSTERY },
  { id: 34, name: 'I-70 Killer Corridor', coordinates: [39.0997, -94.5786], category: LocationCategory.MYSTERY },
  { id: 35, name: 'Jacqueline Lard Murder', coordinates: [38.7447, -90.2831], category: LocationCategory.CRIME },
  { id: 36, name: 'Amy Baker Murder', coordinates: [38.5833, -90.3167], category: LocationCategory.CRIME },
  { id: 37, name: 'Disappearance of Tara Calico', coordinates: [34.5461, -106.8906], category: LocationCategory.MYSTERY },
  { id: 38, name: 'Disappearance of Maura Murray', coordinates: [44.1167, -71.7833], category: LocationCategory.MYSTERY },
  { id: 39, name: "Amelia Earhart's Last Known Area", coordinates: [ -0.8713, -176.6234], category: LocationCategory.MYSTERY },
];

export const MOCK_LOCATION_DETAILS: Record<number, LocationFull> = {
  1: {
    id: 1,
    name: 'The Winchester Mystery House',
    address: '525 S Winchester Blvd, San Jose, CA 95128',
    coordinates: [37.3184, -121.9513],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The house is said to be haunted by the ghost of Sarah Winchester and the spirits of those killed by Winchester rifles. Visitors report doors slamming, disembodied voices, and ghostly apparitions wandering the endless maze of hallways.',
      crimeAndPunishment: 'No specific crimes are associated with the house itself, but its construction was funded by the "blood money" from the Winchester Repeating Arms Company, a weapon that played a significant role in the American West.',
      socialHistory: 'Construction began in 1886 and continued, 24 hours a day, until Sarah Winchester\'s death in 1922. The house is an architectural marvel and a monument to one woman\'s obsession and grief, featuring stairways to nowhere and doors that open into walls.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Winchester_Mystery_House_San_Jose.jpg', caption: 'Aerial view of the sprawling mansion.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Winchester_Mystery_House_April_2013_008.jpg/1280px-Winchester_Mystery_House_April_2013_008.jpg', caption: 'The infamous Séance Room.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Stairs_to_nowhere_at_Winchester_Mystery_House.jpg/1280px-Stairs_to_nowhere_at_Winchester_Mystery_House.jpg', caption: 'A staircase leading to the ceiling.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Winchester_Mystery_House_April_2013_018.jpg/1280px-Winchester_Mystery_House_April_2013_018.jpg', caption: 'Intricate stained glass window.' },
    ],
    tags: ['19th Century', 'Gilded Age', 'Spiritualism'],
    warning: 'This is a popular tourist destination. Please respect the property and staff.'
  },
  2: {
    id: 2,
    name: 'Alcatraz Island',
    address: 'Alcatraz Island, San Francisco, CA 94133',
    coordinates: [37.8270, -122.4230],
    category: LocationCategory.CRIME,
    dossier: {
      spiritStories: 'Known as "The Rock," Alcatraz is considered one of America\'s most haunted prisons. Former inmates and guards have reported hearing screams, cell doors clanging, and the phantom sound of a banjo from Al Capone\'s old cell.',
      crimeAndPunishment: 'Housed some of the most notorious criminals in American history, including Al Capone, "Machine Gun" Kelly, and Robert Stroud, the "Birdman of Alcatraz." The prison was designed to be escape-proof, though the 1962 escape by Frank Morris and the Anglin brothers remains an enduring mystery.',
      socialHistory: 'Before becoming a federal prison in 1934, Alcatraz was a military fort. It operated as a prison until 1963. The harsh conditions and psychological isolation were legendary, making it the ultimate punishment in the U.S. justice system.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Alcatraz_Island_2018.jpg/1920px-Alcatraz_Island_2018.jpg', caption: 'View of the prison from the bay.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Alcatraz_cell_block_2008.jpg/1920px-Alcatraz_cell_block_2008.jpg', caption: 'A typical cell block.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Alcatraz_Guard_Tower.jpg/1280px-Alcatraz_Guard_Tower.jpg', caption: 'The main guard tower.' },
    ],
    tags: ['20th Century', 'Prohibition', 'Great Depression'],
  },
  3: {
    id: 3,
    name: 'The Villisca Axe Murder House',
    address: '508 E 2nd St, Villisca, IA 50864',
    coordinates: [40.9329, -94.9750],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'Visitors and paranormal investigators report hearing the cries of children, seeing inexplicable visions, and feeling a heavy presence, believed to be the spirits of the murdered Moore family still seeking justice.',
      crimeAndPunishment: 'In 1912, the six members of the Moore family and two young houseguests were found bludgeoned to death in their beds. The brutal crime was never solved, leaving a dark stain on the town and creating one of America\'s greatest unsolved mysteries.',
      socialHistory: 'The murders terrified the small, close-knit community of Villisca, Iowa. The investigation was plagued by mishandling and suspicion fell on several individuals, but no one was ever convicted, leaving the town forever changed.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Villisca-Axe-Murder-House-Villisca-Iowa.jpg/1920px-Villisca-Axe-Murder-House-Villisca-Iowa.jpg', caption: 'The unassuming exterior of the house.' },
    ],
    tags: ['20th Century', 'Unsolved Mystery', 'Iowa'],
  },
  4: {
    id: 4,
    name: 'Eastern State Penitentiary',
    address: '2027 Fairmount Ave, Philadelphia, PA 19130',
    coordinates: [39.9683, -75.1725],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'A former prison known for its solitary confinement and now home to unsettling echoes and ghostly figures. Shadowy figures are seen darting down halls, disembodied wails come from empty cells, and a ghostly locksmith is said to haunt the grounds.',
      crimeAndPunishment: 'Pioneered the "Pennsylvania system" of solitary confinement, which was intended to inspire penitence but often drove inmates to madness. It housed infamous criminals like Al Capone and bank robber Willie Sutton.',
      socialHistory: 'Opened in 1829, it was one of the most expensive and influential prisons of its time, representing a new, ambitious philosophy of prison reform. Its crumbling, Gothic architecture now stands as a haunting monument to a failed experiment.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Eastern_State_Penitentiary_from_Fairmount_Avenue.JPG/1920px-Eastern_State_Penitentiary_from_Fairmount_Avenue.JPG', caption: 'The imposing facade of the penitentiary.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Cell_block_at_Eastern_State_Penitentiary.jpg/1920px-Cell_block_at_Eastern_State_Penitentiary.jpg', caption: 'A crumbling, sky-lit cell block.' },
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Al_Capone%27s_cell_at_Eastern_State_Penitentiary.jpg/1280px-Al_Capone%27s_cell_at_Eastern_State_Penitentiary.jpg', caption: 'Al Capone\'s restored cell.' },
    ],
    tags: ['19th Century', 'Prison Reform', 'Gothic Architecture'],
  },
  5: {
    id: 5,
    name: 'Lizzie Borden House',
    address: '230 2nd St, Fall River, MA 02721',
    coordinates: [41.7006, -71.1565],
    category: LocationCategory.CRIME,
    dossier: {
      spiritStories: 'Now a bed and breakfast, guests at the site of the famous axe murders report experiencing chilling phenomena. Many claim to hear a woman weeping, see apparitions in Victorian clothing, and feel phantom touches, particularly in the rooms where the bodies were found.',
      crimeAndPunishment: 'In 1892, Andrew and Abby Borden were brutally murdered with a hatchet. Their daughter, Lizzie Borden, was the primary suspect in one of the most sensational trials in American history. Despite her acquittal, the question of her guilt remains a subject of intense debate.',
      socialHistory: 'The case captivated the nation, highlighting the strict social mores and class divisions of Gilded Age New England. The famous rhyme, "Lizzie Borden took an axe...", cemented the story in American folklore.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Lizzie_Borden_House_2009.jpg/1920px-Lizzie_Borden_House_2009.jpg', caption: 'The infamous house, now a museum and B&B.' },
    ],
    tags: ['19th Century', 'Unsolved Mystery', 'Gilded Age'],
  },
  6: {
    id: 6,
    name: "Jack the Ripper's London",
    address: 'Whitechapel, London, UK',
    coordinates: [51.5186, -0.0740],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The cobbled alleyways of Whitechapel are said to be haunted by the spirits of the Ripper\'s victims. People report sudden cold spots, the scent of phantom perfume, and fleeting glimpses of women in period dress who vanish into the fog.',
      crimeAndPunishment: 'In 1888, a series of gruesome murders attributed to "Jack the Ripper" terrified London. The killer was never identified, creating one of the most enduring criminal mysteries in the world. The case highlighted the shortcomings of Victorian-era police work.',
      socialHistory: 'The murders exposed the brutal poverty and desperate living conditions in London\'s East End. The media frenzy surrounding the case marked a new era of sensationalist journalism.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Whitechapel_High_Street_-_geograph.org.uk_-_296225.jpg/1920px-Whitechapel_High_Street_-_geograph.org.uk_-_296225.jpg', caption: 'A street in Whitechapel, reminiscent of the era.' },
    ],
    tags: ['19th Century', 'Victorian Era', 'Serial Killer'],
  },
  7: {
    id: 7,
    name: 'Old Town Saloon (User Submitted)',
    address: 'Los Angeles, CA',
    coordinates: [34.0522, -118.2437],
    category: LocationCategory.USER,
    dossier: {
      spiritStories: 'Locals claim the ghost of a Gold Rush prospector named "Silas" haunts this old watering hole. He\'s known to slide glasses down the bar, whisper in patrons\' ears, and flicker the lights whenever someone tries to sit at his favorite stool.',
      crimeAndPunishment: 'Legend says Silas was shot in the back during a high-stakes poker game in 1851 after being accused of cheating. His murderer was never caught, and Silas has been waiting for a rematch ever since.',
      socialHistory: 'The saloon is one of the oldest buildings in the area, a relic of the city\'s wild, early days during the California Gold Rush. It has served as a bar, a brothel, and a hideout over its long history.',
    },
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1585620257599-purchase-44f2a8d?q=80&w=2940&auto=format&fit=crop', caption: 'The rustic bar inside an old-style saloon.' },
    ],
    tags: ['Gold Rush', 'Old West', 'Local Legend'],
    warning: 'This is a user-submitted location. Information may not be historically verified.'
  },
  8: {
    id: 8,
    name: 'Lord Baltimore Hotel',
    address: '20 W Baltimore St, Baltimore, MD 21201',
    coordinates: [39.2885, -76.6180],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The hotel is famously haunted by the ghost of a young girl named Lulu, often seen in a white dress bouncing a red ball. Guests also report sightings of a couple who allegedly jumped from the roof during the Great Depression, their spirits forever replaying the tragic event.',
      crimeAndPunishment: 'During Prohibition, the hotel was a hotspot for Baltimore\'s high society and, allegedly, its criminal underworld. Secret deals and illicit activities were rumored to take place within its opulent rooms.',
      socialHistory: 'Opened in 1928, the Lord Baltimore Hotel was one of the most elegant landmarks in the city. Its French Renaissance architecture stood as a symbol of prosperity before the economic crash of 1929.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Lord_Baltimore_Hotel_%282008%29.jpg/1280px-Lord_Baltimore_Hotel_%282008%29.jpg', caption: 'The grand lobby of the Lord Baltimore Hotel.' },
    ],
    tags: ['1920s', 'Great Depression', 'Hotel'],
  },
  9: {
    id: 9,
    name: 'Castillo de San Marcos',
    address: '1 S Castillo Dr, St. Augustine, FL 32084',
    coordinates: [29.8976, -81.3113],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The fort is said to be haunted by Spanish soldiers still standing guard. The most famous legend tells of a tragic love affair between a colonel\'s wife and a captain, whose spirits were allegedly sealed alive within a dungeon and remain there to this day.',
      crimeAndPunishment: 'The fort served as a military prison for centuries. Punishments were harsh, and it was the site of numerous battles and sieges, leading to countless deaths within and around its walls.',
      socialHistory: 'As the oldest masonry fort in the continental United States, the Castillo is a monument to centuries of colonial conflict between Spain, Great Britain, and the early United States. Its coquina walls absorbed cannon fire rather than shattering, making it nearly impenetrable.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Castillo_de_San_Marcos_%28St._Augustine%2C_Florida%29.jpg/1920px-Castillo_de_San_Marcos_%28St._Augustine%2C_Florida%29.jpg', caption: 'The iconic coquina walls of the fort at sunset.' },
    ],
    tags: ['Colonial Era', 'Military History', 'Florida'],
  },
  10: {
    id: 10,
    name: 'St. Augustine Lighthouse',
    address: '100 Red Cox Dr, St. Augustine, FL 32080',
    coordinates: [29.8851, -81.2882],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The lighthouse is haunted by the playful spirits of two young girls who drowned in a tragic accident during its construction. Visitors report hearing children\'s laughter, footsteps on the stairs, and seeing the ghost of a former lighthouse keeper who is still watching over the coast.',
      crimeAndPunishment: 'No major crimes are associated with the site, but the life of a lighthouse keeper was one of isolation and immense responsibility, where a single mistake could lead to a shipwreck and the loss of many lives.',
      socialHistory: 'The current lighthouse was built in 1874 and is a vital piece of St. Augustine\'s maritime history. It has guided ships safely into the nation\'s oldest port for nearly 150 years.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/St._Augustine_Lighthouse_after_Hurricane_Dora.jpg/1280px-St._Augustine_Lighthouse_after_Hurricane_Dora.jpg', caption: 'The iconic black and white striped lighthouse.' },
    ],
    tags: ['19th Century', 'Maritime History', 'Florida'],
  },
  11: {
    id: 11,
    name: 'Old Jail, St. Augustine',
    address: '167 San Marco Ave, St. Augustine, FL 32084',
    coordinates: [29.9079, -81.3149],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The spirits of former inmates, including those executed on the gallows, are said to linger. Paranormal activity includes disembodied voices, cell doors slamming shut, and the overwhelming feeling of being watched by unseen eyes in the dark, cramped cells.',
      crimeAndPunishment: 'Operating from 1891 to 1953, the jail housed violent criminals under brutal conditions. It featured a maximum-security section and a gallows where several hangings took place, contributing to its dark and oppressive atmosphere.',
      socialHistory: 'Built by the same company that constructed Alcatraz, the Old Jail was designed to look like a hotel to appease tourists. This facade hid the grim reality of the justice and penal systems of the era.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Old_Jail_in_St._Augustine_Florida.jpg/1920px-Old_Jail_in_St._Augustine_Florida.jpg', caption: 'The historic Old Jail building.' },
    ],
    tags: ['19th Century', 'Penal System', 'Florida'],
  },
  12: {
    id: 12,
    name: 'Gettysburg Battlefield',
    address: 'Gettysburg, PA 17325',
    coordinates: [39.8055, -77.2498],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'Site of a major Civil War battle, with many reports of spectral soldiers and unexplained phenomena. Visitors and investigators have recorded phantom cannon fire, seen apparitions of soldiers reenacting battles in the fields, and captured EVPs of men crying out in pain.',
      crimeAndPunishment: 'The "crime" of Gettysburg was war itself. The battle resulted in over 50,000 casualties, making it the bloodiest battle of the Civil War. The fields became a vast, open grave before proper burials could be conducted.',
      socialHistory: 'The battle was a turning point in the Civil War. President Abraham Lincoln\'s subsequent Gettysburg Address is one of the most famous speeches in American history, redefining the purpose of the war.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Gettysburg_National_Military_Park_01.jpg/1920px-Gettysburg_National_Military_Park_01.jpg', caption: 'Cannons on the Gettysburg Battlefield.' },
    ],
    tags: ['Civil War', 'Military History', 'Pennsylvania'],
  },
  13: {
    id: 13,
    name: 'Salem Witch Trials Memorial',
    address: '24 Liberty St, Salem, MA 01970',
    coordinates: [42.5201, -70.8950],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'Infamous for the 17th-century witch trials, the town is filled with a variety of spooky sites and a notorious, witchy atmosphere. The spirits of the 19 innocent people executed for witchcraft are said to haunt the town, seeking acknowledgment of their unjust deaths.',
      crimeAndPunishment: 'The Salem witch trials of 1692 were a horrifying instance of mass hysteria and injustice. Accusations based on "spectral evidence" led to the imprisonment of over 200 people and the execution of 19, plus several others who died in prison.',
      socialHistory: 'The trials reflect the extreme religious fervor and social anxieties of Puritanical society in Colonial America. The event serves as a cautionary tale about the dangers of false accusations and unchecked authority.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Salem_Witch_Trials_Memorial_2017.jpg/1920px-Salem_Witch_Trials_Memorial_2017.jpg', caption: 'The stone benches of the Witch Trials Memorial.' },
    ],
    tags: ['Colonial Era', 'Witch Trials', 'Massachusetts'],
  },
  14: {
    id: 14,
    name: 'The Conjuring House',
    address: '1677 Round Top Rd, Burrillville, RI 02830',
    coordinates: [41.9778, -71.6826],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The real-life setting of a famous haunting, this house is said to still be inhabited by spirits. The Perron family, who lived there in the 1970s, were allegedly tormented by a malevolent spirit named Bathsheba Sherman, a suspected witch who cursed the land.',
      crimeAndPunishment: 'Local legends accuse Bathsheba Sherman, who lived on the property in the 19th century, of witchcraft and the murder of an infant. Though never proven, her dark history is believed to be the source of the paranormal activity.',
      socialHistory: 'The case was made famous by paranormal investigators Ed and Lorraine Warren. The story highlights the resurgence of interest in the paranormal in the latter half of the 20th century and became the basis for "The Conjuring" film series.',
    },
    media: [
      { type: 'image', url: 'https://www.boston.com/wp-content/uploads/2021/05/the-conjuring-house-for-sale-60ad2f1e2f98f-scaled.jpeg', caption: 'The isolated farmhouse in rural Rhode Island.' },
    ],
    tags: ['20th Century', 'Paranormal Investigation', 'Rhode Island'],
  },
  15: {
    id: 15,
    name: 'Old New-Gate Prison',
    address: '115 Newgate Rd, East Granby, CT 06026',
    coordinates: [41.9213, -72.7483],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The nation\'s first state prison, with a reputation for paranormal activity. The dark, claustrophobic tunnels of the former copper mine are said to echo with the moans and whispers of the prisoners who were held captive deep underground.',
      crimeAndPunishment: 'Conditions at New-Gate were horrific. Prisoners were housed in the damp, dark mine shafts with minimal food, light, or sanitation, leading to widespread disease and despair.',
      socialHistory: 'Originally a copper mine opened in 1705, it was converted into a prison during the Revolutionary War to hold Loyalists, and later became Connecticut\'s first state prison. It represents a brutal early chapter in American penal history.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Old_New-Gate_Prison_and_Copper_Mine_in_2019.jpg/1920px-Old_New-Gate_Prison_and_Copper_Mine_in_2019.jpg', caption: 'The ruins and entrance to the underground mine tunnels.' },
    ],
    tags: ['18th Century', 'Revolutionary War', 'Connecticut'],
  },
  16: {
    id: 16,
    name: 'Dock Street Theatre',
    address: '135 Church St, Charleston, SC 29401',
    coordinates: [32.7770, -79.9298],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'America\'s first theater is said to be haunted by two ghosts. One is Nettie Dickerson, a lady of the night who frequented the hotel that once stood here and was struck by lightning on the balcony. The other is Junius Booth, father of John Wilkes Booth, who appears in actor\'s garb.',
      crimeAndPunishment: 'No crimes are associated with the theatre, but its history is dramatic, with the original building being destroyed by the Great Fire of 1740.',
      socialHistory: 'Opened in 1736, the Dock Street Theatre was the first building in America designed exclusively for theatrical performances. It has been a central fixture of Charleston\'s vibrant arts and culture scene for centuries.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Dock-Street-Theatre-Charleston-SC.jpg/1920px-Dock-Street-Theatre-Charleston-SC.jpg', caption: 'The beautiful exterior of the historic theatre.' },
    ],
    tags: ['18th Century', 'Theatre', 'South Carolina'],
  },
  17: {
    id: 17,
    name: 'The Marshall House',
    address: '123 E Broughton St, Savannah, GA 31401',
    coordinates: [32.0784, -81.0908],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'A historic hotel in Savannah with a long history of ghostly encounters. It served as a Union hospital during the Civil War, and guests report seeing apparitions of soldiers with missing limbs, hearing the ghosts of children running down the halls, and faucets turning on by themselves.',
      crimeAndPunishment: 'During its time as a hospital, surgeons performed countless amputations under primitive conditions. The grounds are believed to hold the remains of amputated limbs, tying the spirits of soldiers to the location.',
      socialHistory: 'Opened in 1851, The Marshall House is one of the oldest hotels in Savannah. It has witnessed the city\'s evolution through the Civil War, yellow fever epidemics, and its restoration as a historic landmark.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Marshall_House_Hotel%2C_Savannah%2C_Georgia.jpg/1920px-Marshall_House_Hotel%2C_Savannah%2C_Georgia.jpg', caption: 'The elegant ironwork balcony of The Marshall House.' },
    ],
    tags: ['19th Century', 'Civil War', 'Georgia'],
  },
  18: {
    id: 18,
    name: 'Trans-Allegheny Lunatic Asylum',
    address: '71 Asylum Dr, Weston, WV 26452',
    coordinates: [39.0435, -80.4728],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'A massive former asylum with a dark history and numerous reports of paranormal activity. The spirits of former patients who were subjected to horrific treatments like lobotomies and hydrotherapy are said to roam the decaying wards, their tortured cries still echoing through the halls.',
      crimeAndPunishment: 'Designed to hold 250 patients, the asylum was severely overcrowded, at its peak housing over 2,400 people in inhumane conditions. Neglect, abuse, and controversial medical experiments were rampant.',
      socialHistory: 'Constructed from 1858-1881, the asylum is the largest hand-cut stone masonry building in North America. Its history provides a chilling look into the evolution of mental health treatment in the United States.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Trans-Allegheny_Lunatic_Asylum_in_2019.jpg/1920px-Trans-Allegheny_Lunatic_Asylum_in_2019.jpg', caption: 'The sprawling, Gothic asylum.' },
    ],
    tags: ['19th Century', 'Medical History', 'West Virginia'],
  },
  19: {
    id: 19,
    name: 'Sleepy Hollow Cemetery',
    address: '540 N Broadway, Sleepy Hollow, NY 10591',
    coordinates: [41.0950, -73.8631],
    category: LocationCategory.HAUNTED,
    dossier: {
      spiritStories: 'The resting place of author Washington Irving, the cemetery is surrounded by legends of the Headless Horseman. Visitors report hearing phantom hoofbeats and seeing a shadowy rider, especially near the Old Dutch Church and the bridge where Ichabod Crane had his fateful encounter.',
      crimeAndPunishment: 'The primary "crime" is the fictional one from "The Legend of Sleepy Hollow," where the Headless Horseman, the ghost of a Hessian soldier, terrorizes the local inhabitants in search of his lost head.',
      socialHistory: 'The cemetery is the final resting place for many notable figures, including Washington Irving, Andrew Carnegie, and Elizabeth Arden. The local folklore, immortalized by Irving, has made Sleepy Hollow synonymous with American Gothic tales.',
    },
    media: [
      { type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Sleepy_Hollow_Cemetery_sign_and_gate.jpeg/1920px-Sleepy_Hollow_Cemetery_sign_and_gate.jpeg', caption: 'The entrance to Sleepy Hollow Cemetery.' },
    ],
    tags: ['Folklore', 'Literary History', 'New York'],
  },
  20: {
    id: 20,
    name: 'The Black Dahlia Murder',
    address: 'Leimert Park, Los Angeles, CA',
    coordinates: [34.0637, -118.3288],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The tragic spirit of Elizabeth Short is said to haunt the Biltmore Hotel, where she was last seen alive, and the area where her body was discovered. People report a sense of profound sadness and see fleeting apparitions of a woman in black.',
      crimeAndPunishment: 'In 1947, the bisected body of aspiring actress Elizabeth Short was found in a vacant lot. The gruesome murder shocked the nation and sparked a massive investigation, but the killer was never identified, making it one of Hollywood\'s most infamous cold cases.',
      socialHistory: 'The case exposed the dark side of post-war Hollywood glamour, a world of aspiring starlets and powerful men. The media frenzy and numerous false confessions complicated the investigation and cemented the case in public fascination.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Millennium_Biltmore_Hotel_-_Los_Angeles.jpg/1920px-Millennium_Biltmore_Hotel_-_Los_Angeles.jpg', caption: 'The Biltmore Hotel, where Elizabeth Short was last seen.' }],
    tags: ['1940s', 'Unsolved Mystery', 'Hollywood'],
  },
  21: {
    id: 21,
    name: 'Zodiac Killer Territory',
    address: 'Vallejo, CA',
    coordinates: [38.1041, -122.2566],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The areas of the Zodiac\'s attacks are said to carry a lingering sense of dread. Visitors to Lake Berryessa report feeling watched, and some claim the killer\'s taunting spirit still roams the Bay Area, a phantom forever eluding capture.',
      crimeAndPunishment: 'In the late 1960s and early 1970s, a serial killer known as the Zodiac terrorized Northern California. He claimed to have killed 37 people and sent taunting, coded letters to the press. His identity remains one of the greatest mysteries in American criminal history.',
      socialHistory: 'The Zodiac case occurred during a time of social upheaval. His cryptic messages and challenges to law enforcement created a culture of fear and played into the counter-culture anxieties of the era.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Zodiac-z340.gif/1200px-Zodiac-z340.gif', caption: 'A coded message sent by the Zodiac Killer.' }],
    tags: ['1960s', 'Serial Killer', 'Cryptography'],
  },
  22: {
    id: 22,
    name: 'JonBenét Ramsey House',
    address: '749 15th St, Boulder, CO 80302',
    coordinates: [40.0084, -105.2760],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The home where JonBenét was found has been shrouded in sadness. Neighbors and subsequent owners have reported an unsettling atmosphere, while psychics claim the young girl\'s spirit is unable to rest until her killer is brought to justice.',
      crimeAndPunishment: 'In 1996, six-year-old beauty pageant winner JonBenét Ramsey was found murdered in the basement of her family\'s home. The case became a media sensation, with suspicion falling on her parents and brother, but it remains unsolved to this day.',
      socialHistory: 'The case opened a national conversation about child beauty pageants and the pressures placed on children. The intense media scrutiny and bungled investigation created a perfect storm of public fascination and frustration.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/JonBenet_Ramsey_residence.jpg/1920px-JonBenet_Ramsey_residence.jpg', caption: 'The infamous home in Boulder, Colorado.' }],
    tags: ['1990s', 'Unsolved Mystery', 'Media Sensation'],
  },
  23: {
    id: 23,
    name: 'Isabella Stewart Gardner Museum',
    address: '25 Evans Way, Boston, MA 02115',
    coordinates: [42.3380, -71.0991],
    category: LocationCategory.CRIME,
    dossier: {
      spiritStories: 'The empty frames where the stolen masterpieces once hung are said to carry a ghostly weight. Staff and visitors feel a sense of loss and violation, as if the spirits of the artists are mourning their missing works.',
      crimeAndPunishment: 'In 1990, two thieves disguised as police officers broke into the museum and stole 13 works of art, including masterpieces by Vermeer and Rembrandt, valued at $500 million. It is the largest private property theft in history, and the art has never been recovered.',
      socialHistory: 'The audacious heist remains a significant cultural crime. The museum has left the empty frames on the walls as a placeholder for the missing works and a symbol of hope for their return.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Isabella_Stewart_Gardner_Museum_Courtyard.jpg/1280px-Isabella_Stewart_Gardner_Museum_Courtyard.jpg', caption: 'The museum\'s iconic courtyard.' }],
    tags: ['1990s', 'Art Heist', 'Boston'],
  },
  24: {
    id: 24,
    name: 'D.B. Cooper Skyjacking',
    address: 'Ariel, WA',
    coordinates: [45.9929, -122.7012],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The dense forests of Washington state, where Cooper may have landed, are filled with local legends. Some say his ghost, forever clutching a parachute and a bag of money, still wanders the woods, a folk hero who pulled off the perfect crime.',
      crimeAndPunishment: 'In 1971, a man identified as Dan "D.B." Cooper hijacked a Boeing 727, extorted a $200,000 ransom, and parachuted into the night over the Pacific Northwest. He was never seen again, and his identity remains unknown.',
      socialHistory: 'The D.B. Cooper case is the only unsolved skyjacking in U.S. history. It has inspired countless theories, books, and films, turning the mysterious hijacker into an anti-establishment icon.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/D-B-Cooper-Composite-Sketch.jpg/1200px-D-B-Cooper-Composite-Sketch.jpg', caption: 'The composite sketch of hijacker D.B. Cooper.' }],
    tags: ['1970s', 'Unsolved Mystery', 'Aviation'],
  },
  25: {
    id: 25,
    name: 'Disappearance of Jimmy Hoffa',
    address: 'Machus Red Fox, Bloomfield Township, MI',
    coordinates: [42.5484, -83.2880],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The ghost of the powerful and controversial Teamsters union leader is said to haunt the grounds of the restaurant where he was last seen. His spirit is restless, forever tied to the mystery of his final moments and the location of his remains.',
      crimeAndPunishment: 'In 1975, Jimmy Hoffa disappeared from the parking lot of a restaurant. He was scheduled to meet with two Mafia figures. He was declared legally dead in 1982, and though it is widely believed he was murdered by the mob, his body has never been found.',
      socialHistory: 'Hoffa\'s disappearance marked a turning point in the history of American organized labor and its ties to organized crime. The case highlights the immense power and corruption that once defined the Teamsters union.',
    },
    media: [{ type: 'image', url: 'https://i.abcnews.com/abcnews/wireimages/20210729/jimmy-hoffa-ap-ps-210729_1627581512168_hpMain_16x9_992.jpg', caption: 'Historic photo of Jimmy Hoffa.' }],
    tags: ['1970s', 'Organized Crime', 'Missing Person'],
  },
  26: {
    id: 26,
    name: 'Chicago Tylenol Murders',
    address: 'Elk Grove Village, IL',
    coordinates: [42.0334, -87.9167],
    category: LocationCategory.CRIME,
    dossier: {
      spiritStories: 'The random, terrifying nature of the crime left a scar on the Chicago area. A sense of unease still lingers, a reminder of the vulnerability of everyday life and the faceless evil that could strike anywhere.',
      // FIX: Corrected typo in property name from crimeAndPunahment to crimeAndPunishment
      crimeAndPunishment: 'In 1982, seven people in the Chicago metropolitan area died after ingesting Tylenol-branded acetaminophen capsules that had been laced with potassium cyanide. The perpetrator was never caught, and the case led to widespread reforms in the packaging of over-the-counter medications.',
      socialHistory: 'The Tylenol murders caused a nationwide panic and fundamentally changed product safety standards, leading to the introduction of tamper-resistant packaging. The case is a landmark in the history of criminal investigation and public health.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/Tylenol_murders_bottle.png/1024px-Tylenol_murders_bottle.png', caption: 'A recalled bottle of Tylenol from the 1982 incident.' }],
    tags: ['1980s', 'Product Tampering', 'Chicago'],
  },
  27: {
    id: 27,
    name: 'Long Island Serial Killer',
    address: 'Gilgo Beach, NY',
    coordinates: [40.6490, -73.3440],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The desolate stretch of Ocean Parkway where the remains were found is considered a place of profound tragedy. The spirits of the victims are said to haunt the marshes, their stories unresolved and their killer still at large for years.',
      crimeAndPunishment: 'Beginning in 2010, the remains of 10 to 16 people, mostly sex workers, were found along a stretch of Ocean Parkway on Long Island. The case is believed to be the work of an unidentified serial killer, though a suspect was finally arrested in 2023, the full scope of the crimes remains under investigation.',
      socialHistory: 'The case brought attention to the dangers faced by sex workers and the challenges of investigating crimes involving marginalized communities. The years-long search for the killer gripped Long Island and the nation.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Gilgo_Beach_Sign_at_Ocean_Pkwy.jpg/1920px-Gilgo_Beach_Sign_at_Ocean_Pkwy.jpg', caption: 'The sign for Gilgo Beach along Ocean Parkway.' }],
    tags: ['2010s', 'Serial Killer', 'Long Island'],
  },
  28: {
    id: 28,
    name: 'Keddie Cabin Murders',
    address: 'Keddie, CA',
    coordinates: [39.9918, -120.9599],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The site of the demolished Cabin 28 is said to be a hotbed of paranormal activity. The violent, unresolved nature of the crime has left a dark energy, with reports of disembodied screams and feelings of terror from those who visit the area.',
      crimeAndPunishment: 'In 1981, four people were brutally murdered in a cabin at the Keddie Resort in the Sierra Nevada mountains. The investigation was severely flawed from the start, and despite strong suspects, no one was ever charged, leaving the quadruple homicide unsolved.',
      socialHistory: 'The murders shattered the peace of the remote mountain community. The case serves as a chilling example of a botched police investigation and the lasting trauma inflicted on a small town.',
    },
    media: [{ type: 'image', url: 'https://media.abc10.com/assets/KXTV/images/429158742/429158742_1920x1080.jpg', caption: 'The forested area where the Keddie Resort once stood.' }],
    tags: ['1980s', 'Unsolved Mystery', 'California'],
  },
  29: {
    id: 29,
    name: 'The Boy in the Box',
    address: 'Fox Chase, Philadelphia, PA',
    coordinates: [39.9955, -75.1182],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The unknown boy\'s lonely grave has become a site of pilgrimage for those touched by his story. Many feel the spirit of the child lingers, waiting for his name to be known and his story to be told.',
      crimeAndPunishment: 'In 1957, the body of a young boy was found in a cardboard box in a wooded area of Philadelphia. He was badly bruised and appeared to be malnourished. Despite decades of investigation, his identity remained unknown for over 65 years until he was finally identified in 2022 as Joseph Augustus Zarelli. His murder remains unsolved.',
      socialHistory: 'Dubbed "America\'s Unknown Child," the case captured the hearts of investigators and the public for decades. The relentless effort to identify him showcases the dedication of law enforcement and citizen detectives.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/en/5/5a/Boy_in_the_Box_poster.jpg', caption: 'The original police poster for "The Boy in the Box".' }],
    tags: ['1950s', 'Unsolved Mystery', 'Philadelphia'],
  },
  30: {
    id: 30,
    name: 'Texarkana Moonlight Murders',
    address: 'Texarkana, TX',
    coordinates: [33.4418, -94.0660],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The "Phantom Killer" who terrorized Texarkana is said to be a boogeyman whose spirit still haunts the town\'s lover\'s lanes. A sense of fear from that spring of 1946 returns whenever the sun goes down.',
      crimeAndPunishment: 'In the spring of 1946, an unidentified serial killer attacked eight people, killing five, in and around the town of Texarkana. The attacks occurred on weekend nights, often in secluded areas. The killer was never caught, and the case remains officially unsolved.',
      socialHistory: 'The murders caused a mass panic, with residents arming themselves and a city-wide curfew being imposed. The case inspired the classic horror film "The Town That Dreaded Sundown."',
    },
    media: [{ type: 'image', url: 'https://images.newspapers.com/img/img?institutionId=0&user=0&id=71120092&width=557&height=828&crop=170_1091_2592_3822&rotation=0', caption: 'A newspaper clipping from the time of the murders.' }],
    tags: ['1940s', 'Serial Killer', 'Texas'],
  },
  31: {
    id: 31,
    name: 'Bonny Lee Bakley Murder',
    address: 'Studio City, CA',
    coordinates: [34.1444, -118.3842],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The tragic and violent end to a complicated life has left a lingering shadow over this Hollywood-adjacent neighborhood. The unresolved nature of the crime leaves many to feel that justice, and peace for Bonny Lee Bakley, has not yet been found.',
      crimeAndPunishment: 'In May 2001, Bonny Lee Bakley, wife of actor Robert Blake, was shot and killed while sitting in their parked car. Blake was tried and acquitted of the murder, though a civil court later found him liable for her death. The criminal case remains officially unsolved.',
      socialHistory: 'The case was a media spectacle, combining Hollywood celebrity with a convoluted backstory of scams and complex relationships. It highlighted the difference between criminal and civil court standards of proof.',
    },
    media: [{ type: 'image', url: 'https://images.unsplash.com/photo-1620427978297-70f909a354e2?q=80&w=2864&auto=format&fit=crop', caption: 'A quiet residential street at night in Studio City.' }],
    tags: ['2000s', 'Unsolved Mystery', 'Hollywood'],
  },
  32: {
    id: 32,
    name: 'Chandra Levy Disappearance',
    address: 'Rock Creek Park, Washington, D.C.',
    coordinates: [38.9221, -77.0469],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The vast, urban oasis of Rock Creek Park holds a dark secret. The spirit of Chandra Levy is said to be tied to the place where her life was cut short, a tragic reminder of a promising future that was never realized.',
      crimeAndPunishment: 'Chandra Levy, a 24-year-old intern, disappeared in May 2001. Her remains were found a year later. The case garnered massive media attention due to her alleged affair with Congressman Gary Condit. A suspect was convicted but later had his charges dropped, leaving the case officially unsolved.',
      socialHistory: 'The Levy case was a major political scandal at the turn of the century, demonstrating the intersection of crime, politics, and media. It remains a cautionary tale about trial by media and the search for truth.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Boulder_Bridge_in_Rock_Creek_Park_in_Autumn.jpg/1920px-Boulder_Bridge_in_Rock_Creek_Park_in_Autumn.jpg', caption: 'The dense woods of Rock Creek Park.' }],
    tags: ['2000s', 'Political Scandal', 'Missing Person'],
  },
  33: {
    id: 33,
    name: 'Marsha Brantley Disappearance',
    address: 'Cleveland, TN',
    coordinates: [35.1584, -84.8519],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'A cloud of suspicion and unanswered questions hangs over this Tennessee town. The absence of Marsha Brantley is a ghostly presence, a constant reminder of a life vanished without a trace.',
      crimeAndPunishment: 'Marsha Brantley disappeared in 2009. While law enforcement believes she was murdered by her husband, who was later convicted of embezzling from her, there has never been enough direct evidence to charge him with her murder. Her body has never been found.',
      socialHistory: 'This case is a tragic example of "no body, no crime" hurdles in the justice system. It highlights the anguish of families who are denied closure and the difficulty of proving murder without physical remains.',
    },
    media: [{ type: 'image', url: 'https://images.unsplash.com/photo-1598912444733-069457633c94?q=80&w=2835&auto=format&fit=crop', caption: 'A quiet suburban street in Tennessee.' }],
    tags: ['2000s', 'Missing Person', 'Suspected Murder'],
  },
  34: {
    id: 34,
    name: 'I-70 Killer Corridor',
    address: 'Kansas City, MO',
    coordinates: [39.0997, -94.5786],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'A phantom menace haunts the major artery of the American Midwest. The spirit of the I-70 Killer is a dark legend among truckers and travelers, a specter of the seemingly safe and familiar roadside stop turned deadly.',
      crimeAndPunishment: 'In the spring of 1992, a serial killer shot and killed six store clerks along Interstate 70 in Indiana, Missouri, and Kansas. The killer, believed to be a single individual, was never identified. The cases of Jacqueline Lard and Amy Baker are sometimes linked.',
      socialHistory: 'The spree created terror along a vital commercial and travel route. The case demonstrated the mobility of modern serial offenders and the challenges of multi-jurisdictional investigations in the pre-digital era.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/I-70_East_at_I-435_exit_210.jpg/1920px-I-70_East_at_I-435_exit_210.jpg', caption: 'A view of the I-70 highway.' }],
    tags: ['1990s', 'Serial Killer', 'Midwest'],
  },
  35: {
    id: 35,
    name: 'Jacqueline Lard Murder',
    address: 'St. Louis, MO',
    coordinates: [38.7447, -90.2831],
    category: LocationCategory.CRIME,
    dossier: {
      spiritStories: 'The memory of this brutal crime leaves a cold spot in the community, a haunting reminder of a life taken too soon and a killer who may have been part of a larger, terrifying pattern.',
      crimeAndPunishment: 'In 2000, Jacqueline Lard was found murdered in St. Louis. Her case remains unsolved but is considered by some investigators as a possible work of the notorious I-70 Killer, suggesting a potential return of the dormant serial murderer.',
      socialHistory: 'Lard\'s murder renewed fears in the St. Louis area, bringing back memories of other unsolved cases and the terrifying possibility that a serial killer was once again active in the region.',
    },
    media: [{ type: 'image', url: 'https://images.unsplash.com/photo-1620224694304-99a5b3a32439?q=80&w=2787&auto=format&fit=crop', caption: 'An urban landscape in St. Louis.' }],
    tags: ['2000s', 'Unsolved Murder', 'St. Louis'],
  },
  36: {
    id: 36,
    name: 'Amy Baker Murder',
    address: 'St. Louis, MO',
    coordinates: [38.5833, -90.3167],
    category: LocationCategory.CRIME,
    dossier: {
      spiritStories: 'Like other potential victims of the I-70 Killer, the unresolved nature of Amy Baker\'s murder has left a lingering sense of injustice and fear in the community where she lived and worked.',
      crimeAndPunishment: 'Also in 2000, the unsolved murder of Amy Baker in St. Louis raised alarms. Due to similarities in victimology and method, her case is often discussed in conjunction with Jacqueline Lard and the I-70 Killer.',
      socialHistory: 'This case, along with others, highlighted the vulnerability of store clerks and service workers and led to increased discussions about safety measures in retail environments.',
    },
    media: [{ type: 'image', url: 'https://images.unsplash.com/photo-1594101435032-6b9322a3e018?q=80&w=2854&auto=format&fit=crop', caption: 'A roadside view in suburban St. Louis.' }],
    tags: ['2000s', 'Unsolved Murder', 'St. Louis'],
  },
  37: {
    id: 37,
    name: 'Disappearance of Tara Calico',
    address: 'Belen, NM',
    coordinates: [34.5461, -106.8906],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The desolate highway where Tara was last seen holds a chilling secret. Her spirit is said to be forever riding her pink bicycle, a ghostly image tied to the infamous Polaroid photo that gave hope and horror to her family.',
      crimeAndPunishment: 'In 1988, 19-year-old Tara Calico went for a bike ride and never returned. The case took a bizarre turn a year later when a Polaroid photo of an unidentified young woman and boy, bound and gagged, was found in a parking lot. The woman strongly resembled Calico, but she was never definitively identified, and Tara remains missing.',
      socialHistory: 'The "T-shirt Polaroid" became one of the most haunting and recognizable images in the history of missing persons cases. It symbolizes the desperate hope and deep fear experienced by families of the missing.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/New_Mexico_State_Road_47_map.svg/1280px-New_Mexico_State_Road_47_map.svg.png', caption: 'The desolate stretch of Highway 47 in New Mexico where Tara was last seen.' }],
    tags: ['1980s', 'Missing Person', 'New Mexico'],
  },
  38: {
    id: 38,
    name: 'Disappearance of Maura Murray',
    address: 'Haverhill, NH',
    coordinates: [44.1167, -71.7833],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The sharp turn on Route 112 where Maura crashed her car is a place of endless questions. Some say her confused spirit still wanders the cold New Hampshire woods, lost between this world and the next, her disappearance a modern ghost story of the digital age.',
      crimeAndPunishment: 'In 2004, college student Maura Murray crashed her car on a rural road in New Hampshire and vanished. Despite extensive searches and investigation into her troubled personal life, no trace of her has ever been found. Did she succumb to the elements, get abducted, or start a new life?',
      socialHistory: 'Maura Murray\'s disappearance is one of the first and most prominent internet-age cold cases. It spawned a massive online community of amateur sleuths, podcasts, and documentaries, highlighting the power and pitfalls of crowdsourced investigations.',
    },
    media: [{ type: 'image', url: 'https://images.unsplash.com/photo-1579483321154-47c576085b91?q=80&w=2807&auto=format&fit=crop', caption: 'A winding, snow-covered road in New Hampshire.' }],
    tags: ['2000s', 'Missing Person', 'Internet Phenomenon'],
  },
  39: {
    id: 39,
    name: "Amelia Earhart's Last Known Area",
    address: 'Howland Island, Pacific Ocean',
    coordinates: [-0.8713, -176.6234],
    category: LocationCategory.MYSTERY,
    dossier: {
      spiritStories: 'The ghost of Amelia Earhart and her plane, the Electra, are said to haunt the vast, empty expanse of the Pacific Ocean. A phantom signal, a ghostly whisper on the radio waves, forever searching for a runway that was never found.',
      crimeAndPunishment: 'This is not a crime, but one of the greatest unsolved mysteries of the 20th century. In 1937, pioneering aviator Amelia Earhart and navigator Fred Noonan disappeared over the central Pacific Ocean during an attempt to circumnavigate the globe. No trace of them or their plane was ever definitively found.',
      socialHistory: 'Earhart was a global icon, a symbol of adventure and female empowerment. Her disappearance captured the world\'s imagination and has led to countless theories and expeditions, from crashing at sea to being captured by the Japanese or living as a castaway.',
    },
    media: [{ type: 'image', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Amelia_Earhart_standing_under_nose_of_her_Lockheed_Model_10-E_Electra%2C_small.jpg/1280px-Amelia_Earhart_standing_under_nose_of_her_Lockheed_Model_10-E_Electra%2C_small.jpg', caption: 'Amelia Earhart with her Lockheed Electra plane.' }],
    tags: ['1930s', 'Aviation', 'Historical Mystery'],
  },
};